#!/bin/bash
CELL_ID=`basename ${BASH_SOURCE[0]}`
DICT_CELL=("${DICT_CELL[@]}" $CELL_ID)
DICT=(
"湖南卫视歌手【官方推荐】/71972"
"国家宝藏【官方推荐】/80730"
"歌手人名大全【官方推荐】/20658"
)
eval "${CELL_ID}${DICT_CELL_SUFFIX}=(${DICT[@]})"