#!/bin/bash
CELL_ID=`basename ${BASH_SOURCE[0]}`
DICT_CELL=("${DICT_CELL[@]}" $CELL_ID)
DICT=(
"临床心理学名词/8520"
"应用心理学名词/8523"
"人格心理学名词/8519"
"社会心理学名词/8522"
"心理学词库EXTEND版/12997"
"普通心理学名词/8517"
"心理学词库/600"
"医学心理学/9997"
"心理学/167"
"心理学词汇大全【官方推荐】/15129"
)
eval "${CELL_ID}${DICT_CELL_SUFFIX}=(${DICT[@]})"